- name: HTML
  logo: html5
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=html
  color: E34F26
  logoColor: FFFFFF
  projects:
    - https://github.com/sarthaktexas/ScienceBowlScoreTimer
- name: JavaScript
  logo: javascript
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  logoColor: FFFFFF
  projects:
    - https://github.com/sarthaktexas/website
    - https://github.com/sarthakmohantyinc/Opes
    - https://github.com/sarthaktexas/zoom-dashboard
    - https://github.com/sarthakmohantyinc/Labori
    - https://github.com/sarthaktexas/salamandarian
    - https://github.com/sarthaktexas/discord-user-bot
    - https://github.com/sarthaktexas/send-message-serverless
    - https://github.com/sarthaktexas/home-automation-serverless
    - https://github.com/sarthaktexas/kick-talking-user-discord-bot
- name: Swift
  logo: swift
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=swift
  logoColor: FA7343
  color: FFFFFF
  projects:
    - https://github.com/HackClub/Rudolph
- name: Python
  logo: python
  url: https://github.com/sarthaktexas?tab=repositories&q=&type=&language=python
  logoColor: FFFFFF
  color: 3776AB
  projects:
    - url: https://github.com/sarthaktexas/kahootbot
